# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Fun with Flax"
author: "chicham"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: documentation.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: "https://github.com/chicham/fwf" # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.doctest
    - sphinx.ext.todo
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - sphinx.ext.autosectionlabel
    - sphinx_autodoc_typehints
  config:
    autosummary_generate: True
    numpydoc_show_class_members: False
    autoclass_content: "both" # Add __init__ doc (ie. params) to class summaries
    autodoc_inherit_docstrings: True # If no class summary, inherit base class summary
    autosectionlabel_prefix_document: True
    napoleon_use_ivar: True
    todo_include_todos: True
    template_path: ["_templates"]
